Add Kubernetes segment w/ kele.el
seagle0128/doom-modeline pull request #715
Opened 2024-04-11 12:56 UTC by jinnovation

This PR adds a segment for displaying the currently active Kubectl context and, optionally, the selected default namespace. It sources this information via [`kele.el`](https://github.com/jinnovation/kele.el), which handles config loading and refreshing.

<img width="370" alt="image" src="https://github.com/seagle0128/doom-modeline/assets/1932579/f57c1f47-1769-4c56-8937-497c5753d987">

In future iterations, we can add a local map to allow users to perform basic Kubernetes management tasks via cursor, e.g. switching contexts/namespaces, starting/stopping proxy servers, etc.

2024-04-12 03:59 UTC, seagle0128 requested changes

2024-04-12 03:59 UTC, seagle0128 commented on doom-modeline-segments.el
> +           (help-msg (let* ((msgs (list (format "Current context: %s" ctx))))
Should use `let` here.

2024-04-12 11:39 UTC, jinnovation commented on doom-modeline-segments.el
> +           (help-msg (let* ((msgs (list (format "Current context: %s" ctx))))
done

2024-04-13 00:39 UTC, jinnovation commented
@seagle0128 ready for your review again

2024-04-13 02:47 UTC, merged

2024-04-13 02:52 UTC, seagle0128 commented
Well done! Thank you very much.

BTW, I see the name may be long in the screenshot. I think it's better considering the width limit. Please see. `doom-modeline--segment-visible` and `doom-modeline-always-visible-segments`.

2024-04-13 06:15 UTC, jinnovation commented
Great point, expect a follow-up PR soon (:

On Fri, Apr 12, 2024, at 22:52, Vincent Zhang wrote:
> 
> 
> Well done! Thank you very much.
> 
> BTW, I see the name may be long in the screenshot. I think it's better considering the width limit. Please see. `doom-modeline--segment-visible` and `doom-modeline-always-visible-segments`.
> 
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/seagle0128/doom-modeline/pull/715#issuecomment-2053086381>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAOX2IZEV2YKCCRGHFZYIQ3Y5CMXDAVCNFSM6AAAAABGCIEJ2WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANJTGA4DMMZYGE>.
> You are receiving this because you authored the thread.Message ID: ***@***.***>
>